---
title: "R Notebook"
output: html_notebook
---

```{r include = F}
library(tidyverse)
library(janitor)
library(pROC)
library(caret)

oj <- read_csv("data/orange_juice.csv") %>% clean_names() %>% 
  mutate(q = weekof_purchase %% 52,
         q = if_else(q == 0, 52, q),
         q = case_when(q <= 14 ~ 1,
                       q <= 28 ~ 2,
                       q <= 32 ~ 3,
                       TRUE ~ 4),
         across(c(purchase, store_id, special_ch, special_mm, q), factor)) %>% 
  select(-weekof_purchase, -store7, -store, -price_diff, -list_price_diff,
         -pct_disc_mm, -pct_disc_ch, -sale_price_mm, -sale_price_ch)
```

```{r}
# Data summary after preparation. Week of purchase was converted to quarters to reduce the amount of dummy variables.
summary(oj)
```

```{r}
# The over-fitted model
roc_oj <- oj %>% 
  modelr::add_predictions(glm(purchase ~ ., oj, family = binomial(link = 'logit')), type = "response") %>% 
  roc(response = purchase, predictor = pred)

roc_oj$auc
```

```{r}
# Split test and train
train_index <- createDataPartition(oj$purchase, p = 0.8, list = F)

train <- oj[train_index, ]
test <- oj[-train_index, ]
```


```{r}


train_control <- trainControl(method = "repeatedcv", 
                              number = 5,
                              repeats = 100,
                              savePredictions = T, 
                              classProbs = T, 
                              summaryFunction = twoClassSummary)

model <- train(purchase ~ loyal_ch + disc_ch + disc_mm + price_ch + price_mm, train, method = "glm", family = binomial(link = 'logit'), tuneLength = 5, metric = "ROC", trControl = train_control)

summary(model)
model
```

```{r}
preds <- test %>% 
  modelr::add_predictions(model)

confusionMatrix(reference = preds$purchase, data = preds$pred, mode='everything', positive= "MM")
```

