---
title: "R Notebook"
output: html_notebook
---
```{r}
source("clean_data.R")
library(ggrepel)
```

## This is a notebook to explore the data and test different plot options

```{r}
# best developer by critic by year
games %>% 
  group_by(year, developer) %>%
  summarise(meta_score = mean((critic_score + user_score) / 2)) %>% 
  slice_max(meta_score) %>% 
  ggplot(aes(year, meta_score, fill = developer)) + 
    geom_col(position = "dodge")

```
```{r}
games %>% 
  group_by(year) %>% 
  slice_max(sales) %>% 
  select(name, sales, year) %>% 
  ggplot(aes(year, sales)) +
  scale_x_discrete() +
  geom_point() +
  geom_text_repel(aes(label = name))
```
```{r}
games %>% 
  ggplot(aes(critic_score, sales)) +
  geom_point()
 scale_y_continuous(limits = c(0.1, 2))
```


```{r}
# best developer by sales by year
games %>% 
  group_by(year, developer) %>%
  summarise(total_sales = sum(sales)) %>% 
  filter(developer %in% c("Nintendo", "Ubisoft")) %>%
  filter(year >= 2000 & year <= 2015) %>% 
  ggplot(aes(year, total_sales, fill = developer)) + 
  geom_col(position = "dodge") +
  theme_minimal() +
  scale_fill_brewer(palette = "Dark2") +
  labs(x = "\n Year",
       y = "Total sales (million units) \n",
       fill = "Game Developer")  
```
```{r}
# sales by Nintendo by by year
games %>% 
  group_by(year, developer) %>%
  summarise(total_sales = sum(sales)) %>% 
  filter(developer == "Nintendo") %>% 
  ggplot(aes(year, total_sales,)) + 
    geom_col() +
  geom_line()
```

